// Code generated by templ@v0.2.334 DO NOT EDIT.

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/murasakiwano/fitcon/fitconner"

func UserTable(fc fitconner.FitConner) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"card\" class=\"container mx-auto dark:bg-gray-700\"><div class=\"mx-auto max-w-xl overflow-hidden rounded-lg bg-white shadow-xl dark:bg-gray-700\"><div class=\"flex items-center justify-between p-6\"><h1 class=\"text-xl font-semibold text-gray-700 dark:text-gray-100\">")
		if err != nil {
			return err
		}
		var_2 := `Suas metas no FitCon`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><img src=\"path_to_your_logo.png\" alt=\"Logo\" class=\"h-12 w-auto\"></div><table class=\"min-w-full divide-y divide-gray-200\"><tbody class=\"bg-gray-50 dark:bg-gray-700\"><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_3 := `Matrícula`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_4 string = fc.ID
		_, err = templBuffer.WriteString(templ.EscapeString(var_4))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_5 := `Equipe`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_6 string = fc.TeamName
		_, err = templBuffer.WriteString(templ.EscapeString(var_6))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_7 := `Nome`
		_, err = templBuffer.WriteString(var_7)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_8 string = fc.Name
		_, err = templBuffer.WriteString(templ.EscapeString(var_8))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_9 := `Equipe`
		_, err = templBuffer.WriteString(var_9)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_10 string = fc.TeamName
		_, err = templBuffer.WriteString(templ.EscapeString(var_10))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\" rowspan=\"2\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_11 := `Meta 1`
		_, err = templBuffer.WriteString(var_11)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var_12 := `Percentual de Gordura`
		_, err = templBuffer.WriteString(var_12)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_13 string = fc.Goal1FatPercentage
		_, err = templBuffer.WriteString(templ.EscapeString(var_13))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var_14 := `Massa Magra`
		_, err = templBuffer.WriteString(var_14)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_15 string = fc.Goal1LeanMass
		_, err = templBuffer.WriteString(templ.EscapeString(var_15))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\" rowspan=\"3\"><div class=\"text-sm font-medium text-gray-900 dark:text-gray-50\">")
		if err != nil {
			return err
		}
		var_16 := `Meta 2`
		_, err = templBuffer.WriteString(var_16)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"dark:text-gray-3000 text-sm text-gray-50\">")
		if err != nil {
			return err
		}
		var_17 := `Gordura Visceral`
		_, err = templBuffer.WriteString(var_17)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_18 string = fc.Goal2VisceralFat
		_, err = templBuffer.WriteString(templ.EscapeString(var_18))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var_19 := `Gordura Corporal`
		_, err = templBuffer.WriteString(var_19)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_20 string = fc.Goal2FatPercentage
		_, err = templBuffer.WriteString(templ.EscapeString(var_20))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr><tr><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var_21 := `Massa Magra`
		_, err = templBuffer.WriteString(var_21)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td><td class=\"whitespace-nowrap px-6 py-4\"><div class=\"text-sm text-gray-500 dark:text-gray-300\">")
		if err != nil {
			return err
		}
		var var_22 string = fc.Goal2LeanMass
		_, err = templBuffer.WriteString(templ.EscapeString(var_22))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</div></td></tr></tbody></table></div><div class=\"p-6\"><a hx-get=\"/home\" hx-target=\"#card\" class=\"inline-flex items-center rounded-md border border-transparent bg-orange-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-orange-700\">")
		if err != nil {
			return err
		}
		var_23 := `← Voltar `
		_, err = templBuffer.WriteString(var_23)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
